#!/bin/bash
#this is a script I use periodically to remove all zip and tar.gz files from my downloads folder.
#you could add in other file types here pretty easily.
#just add ~/Downloads/*.yourfiletype to the next line.
rm ~/Downloads/*.zip ~/Downloads/*.tar.gz
