#!/bin/bash

#this script sucks. But, I'm keeping it here so you know what NOT to do.

cd ~/.wallpapers

if [ -z "$1" ] #if the script is called with no arguments, randomly select anything from the wallpaper folder
then
	feh --bg-fill --randomize --recursive *
elif [ "${1,,}" == "snowy" ] #here is what I'm gonna call a custom keyword. It selects an image from the snowy folder, hidden in my nature folder
then
	feh --bg-fill --randomize --recursive nature/snowy
else #this takes the argument, and will select any image hidden, in a folder, having that name, from the top level of the wallpapers folder.
     #It can't search for nested folders in the wallpapers directory though, for that, you'll have to do what I did with "snowy", and create a custom elif.
	feh --bg-fill --randomize --recursive "$1"/*
fi


